---
- name: "Playbook to test the inventory_hostname and ansible_hostname"
  hosts: localhost
  gather_facts: yes
  tasks:

    - name: What is my inventory_hostname
      debug: var={{inventory_hostname}}
